version: '3.5'

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=comentarios
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      backend:
        aliases:
          - mysql-db
    
networks:
  backend: